### ISSUE TITLE
Why is the address field in framebuffer a Ptr<u8>?

### ISSUE THREAD

**Issue by Shinribo** [limine-bootloader/limine-rs#22]
Why is the address field in framebuffer a Ptr<u8>? The original type supplied by the Bootloader is *void why not cast it to a u64 as the limine protocol targets 64bit systems.

**Comment by TobiasSN** [comment]
Because `*void` is a pointer. It points to something in memory. `Ptr<T>` is a convenience wrapper around a `Option<NonNull<T>>`, ie. a pointer that may be null. In the end, you will need a pointer (`*T`) or a reference (`&T`) anyway, having a `u64` would just require you to cast it yourself.

**Comment by Shinribo** [comment]
do you know how much confusion it causes if you set address as a ptr<u8> without a comment instead of either setting the type to Option<u64> or adding a comment that the value the ptr points to is the first byte of the fb? Also Fun Fact i would have less code if it was supplied as Option<u64> as when i want to write to a specific pixel i still have to cast it to a u64.

**Comment by Shinribo** [comment]
do you know how much confusion it causes if you set address as a ptr without a comment instead of either setting the type to Option or adding a comment that the value the ptr points to is the first byte of the fb? Also Fun Fact i would have less code if it was supplied as Option as when i want to write to a specific pixel i still have to cast it to a u64.

**Comment by Shinribo** [comment]
an idiot admires complexity a genius admires simplicity

**Comment by lukflug** [comment]
> an idiot admires complexity a genius admires simplicity

In that case, use C.
