### ISSUE TITLE
EntryPointRequest::with_entry_point doesn't allow unsafe function as argument

### ISSUE THREAD

**Issue by bjorn3** [limine-bootloader/limine-rs#25]
My entrypoint is defined in inline asm to capture the stack pointer. Because of this I use `extern "C" { fn limine_entrypoint() -> !; }`, which results in a function signature of `unsafe extern "C" fn() -> !`, which can't be passed to a function that expects `extern "C" fn() -> !`. The former function signature is more correct anyway as the entrypoint may depend on getting called with all state in accordance with the limine boot protocol for safety.

**Comment by lylythechosenone** [comment]
Taking an `unsafe` function here does not make sense, as calling it requires knowing the safety contract. You can simply use something similar to the below code instead. This way, *you* are explicitly owning any UB that the function causes, rather than this library.

```rust
{
    extern "C" fn wrapper() -> ! {
        unsafe { the_function() }
    }
    wrapper
}
```

**Comment by bjorn3** [comment]
> You can simply use something similar to the below code instead.

That doesn't work for my case as it would cause the stack pointer for inline asm to be different from that the bootloader set it too. I ended up transmuting the pointer instead.

**Comment by lylythechosenone** [comment]
You could also look into naked functions. I do wonder, how are you creating the `unsafe` function in the first place? If you need the stack pointer to be exactly the same, you'd ideally be jumping directly into asm, not into a function.

**Comment by bjorn3** [comment]
I defined my function in asm using `.globl my_entry; my_entry:` However to get a function pointer I used:

```rust
extern "C" {
    fn my_entry() -> !;
}
```

which when casting `my_entry` to a function pointer results in the type `unsafe extern "C" fn() -> !`.

**Comment by lylythechosenone** [comment]
Ah, that explains it. I suppose transmuting it is probably fine, then.
